version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: hackaton-api-container
    hostname: api
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=tomyj
      - DB_PASSWORD=tomyj123
      - DB_NAME=db
    ports:
      - "2020:2020"
    networks:
      - hackaton-network
    restart: unless-stopped

  db:
    build:
      context: ./bdd
      dockerfile: Dockerfile
    container_name: hackaton-db-container
    hostname: db
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: tomyj
      MYSQL_PASSWORD: tomyj123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hackaton-network
    restart: unless-stopped

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: hackaton-front-container
    hostname: front
    ports:
      - "30033:80"
    environment:
      - API_HOSTNAME=api
    depends_on:
      - api
    networks:
      - hackaton-network
    restart: unless-stopped

networks:
  hackaton-network:

volumes:
  mysql_data:
